# Generated by Django 5.2.8 on 2025-11-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Резервування'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['numder'], 'verbose_name': 'Приміщення'},
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sur_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('all_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
            ],
            options={
                'verbose_name': 'Користувач/ка',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['name', 'sur_name'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservation.user'),
        ),
    ]
