# Generated by Django 5.2.8 on 2025-11-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_booking_options_alter_room_options_room_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Приміщення'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='numder',
            new_name='number',
        ),
    ]
