# Generated by Django 5.2.8 on 2025-11-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_booking_user_profile_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Резервування', 'verbose_name_plural': 'Резервування'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Приміщення', 'verbose_name_plural': 'Приміщення'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='locations',
            new_name='aboute_room',
        ),
    ]
