# Generated by Django 5.2.8 on 2025-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_booking_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='aboute_room',
            new_name='locations',
        ),
    ]
